import LocalizedStrings from 'react-native-localization';

let strings = new LocalizedStrings({
    en: {
        "Add Food": "Add Food",
        "Add to meal Occasion" : "Add to meal Occasion",
        "Do you have any medical conditions?" : "Do you have any medical conditions?",
        "Email" : "Email",
        "Exercise": "Exercise",
        "Extreme" : "Extreme",
        "Featured" : "Featured",
        "First name (min. 3 characters)" : "First name (min. 3 characters)",
        "Food": "Food",
        "Forgotten your password?" : "Forgotten your password?",
        "Gain weight" : "Gain weight",
        "Get reminders about your diet tracking and health tips" : "Get reminders about your diet tracking and health tips",
        "Get started" : "Get started",
        "Goals": "Goals",
        "Heavy" : "Heavy",
        "I’m already a member" : "I’m already a member",
        "Is there anything you want to improve about your sleep?" : "Is there anything you want to improve about your sleep?",
        "Left" : "Left",
        "Lose weight" : "Lose weight",
        "Macronutrients" : "Macronutrients",
        "Maintain weight" : "Maintain weight",
        "Meals" : "Meals",
        "Mild" : "Mild",
        "Moderate" : "Moderate",
        "Next" : "Next",
        "Nutrition info": "Nutrition info",
        "Nutrients": "Nutrients",
        "Password" : "Password",
        "Password (min. 6 characters)" : "Password (min. 6 characters)",
        "Preferred rate of weight loss?" : "Preferred rate of weight loss?",
        "Sedentary" : "Sedentary",
        "(select all that apply)" : "(select all that apply)",
        "Select activity level?" : "Select activity level?",
        "Serving size" : "Serving size",
        "Set your target weight?" : "Set your target weight?",
        "Set realistic target weight, we recommend no more than 10%." : "Set realistic target weight, we recommend no more than 10%.",
        "Sign in" : "Sign in",
        "Today": "Today",
        "Total": "Total",
        "To have more energy." : "To have more energy.",
        "To feel good in my body." : "To feel good in my body.",
        "To be able to physically do more." : "To be able to physically do more.",
        "Do take fewer medications." : "Do take fewer medications.",
        "To have more confidence." : "To have more confidence.",
        "To be healthier." : "To be healthier.",
        "Type" : "Type",
        "We use this to calculate your calorie target" : "We use this to calculate your calorie target",
        "What do you want to search?" : "What do you want to search?",
        "What’s your goal ?" : "What’s your goal ?",
        "Why do you choose that goal?" : "Why do you choose that goal?",
    },
    "ms-MY": {
        "Add Food": "Add Food",
        "Add to meal Occasion" : "Add to meal Occasion",
        "Do you have any medical conditions?" : "Do you have any medical conditions?",
        "Email" : "Email",
        "Exercise": "Exercise",
        "Extreme" : "Extreme",
        "Featured" : "Featured",
        "First name (min. 3 characters)" : "First name (min. 3 characters)",
        "Food": "Food",
        "Forgotten your password?" : "Forgotten your password?",
        "Gain weight" : "Gain weight",
        "Get reminders about your diet tracking and health tips" : "Get reminders about your diet tracking and health tips",
        "Get started" : "Get started",
        "Goals": "Goals",
        "Heavy" : "Heavy",
        "I’m already a member" : "I’m already a member",
        "Is there anything you want to improve about your sleep?" : "Is there anything you want to improve about your sleep?",
        "Left" : "Left",
        "Lose weight" : "Lose weight",
        "Macronutrients" : "Macronutrients",
        "Maintain weight" : "Maintain weight",
        "Meals" : "Meals",
        "Mild" : "Mild",
        "Moderate" : "Moderate",
        "Next" : "Next",
        "Nutrition info": "Nutrition info",
        "Nutrients": "Nutrients",
        "Password" : "Password",
        "Password (min. 6 characters)" : "Password (min. 6 characters)",
        "Preferred rate of weight loss?" : "Preferred rate of weight loss?",
        "Sedentary" : "Sedentary",
        "(select all that apply)" : "(select all that apply)",
        "Select activity level?" : "Select activity level?",
        "Serving size" : "Serving size",
        "Set your target weight?" : "Set your target weight?",
        "Set realistic target weight, we recommend no more than 10%." : "Set realistic target weight, we recommend no more than 10%.",
        "Sign in" : "Sign in",
        "Today": "Today",
        "Total": "Total",
        "To have more energy." : "To have more energy.",
        "To feel good in my body." : "To feel good in my body.",
        "To be able to physically do more." : "To be able to physically do more.",
        "Do take fewer medications." : "Do take fewer medications.",
        "To have more confidence." : "To have more confidence.",
        "To be healthier." : "To be healthier.",
        "Type" : "Type",
        "We use this to calculate your calorie target" : "We use this to calculate your calorie target",
        "What do you want to search?" : "What do you want to search?",
        "What’s your goal ?" : "What’s your goal ?",
        "Why do you choose that goal?" : "Why do you choose that goal?",
    }
});

// strings.setLanguage('ms-MY');
export default strings